# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bb5dde2cbe5a5ec7ed1ee7cdfafcc72f1f5e7e739f754ac73fd4a7a4db9948c14dd4b0e9139b61b9327e571c210bd11c887961ffbcc7041e4a15b79a1f4f46d

test:
  secret_key_base: e098eafe5528d31b25392990c14e1146e9b2b36ee24d235007ac8b46c5342c2ff9be2cd1b67c999da66b0f3c5261384f4d29f3bc40fe08dd55ac00bbe2c75e8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
